name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server-integration-test-var: [ 'standalone', 'h2', 'mongo', 's3', 'hdfs'] 
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests and install
        run: ./gradlew check installDist -i

      - name: Build Docker image
        run: |
          docker build -t georocket/georocket .
          docker tag georocket/georocket georocket/georocket:unstable

      - name: Run integration tests standalone
        if: server-integration-test-var == "standalone"
        run: |
          cd georocket-server/integration-tests
          ./test-one.sh standalone
          cd ../..
      - name: Run integration tests h2
        if: server-integration-test-var == "h2"
        run: |
          cd georocket-server/integration-tests
          ./test-one.sh h2
          cd ../..

      - name: Run integration tests mongo
        if: server-integration-test-var == "mongo"
        run: |
          cd georocket-server/integration-tests
          ./test-one.sh mongo
          cd ../..
      - name: Run integration tests s3
        if: server-integration-test-var == "s3"
        run: |
          cd georocket-server/integration-tests
          ./test-one.sh s3
          cd ../.
          
      - name: Run integration tests hdfs
        if: server-integration-test-var == "hdfs"
        run: |
          cd georocket-server/integration-tests
          ./test-one.sh hdfs
          cd ../..

      - name: Upload snapshot
        if: github.repository == 'georocket/georocket' && github.event_name == 'push'
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_sonatypePassword }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_sonatypeUsername }}
        run: |
          if [[ $(./gradlew -q :georocket-server:getVersion) == *SNAPSHOT* ]]; then
            ./gradlew upload;
          fi

      - name: Push Docker image
        if: github.repository == 'georocket/georocket' && github.event_name == 'push'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin
          docker push georocket/georocket:unstable
